repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        name: Terraform format
        description: Rewrites all Terraform configuration files to a canonical format
        entry: terraform fmt
        language: system
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$

      - id: terraform_validate
        name: Terraform validate
        description: Validates all Terraform configuration files
        entry: terraform validate
        language: system
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$

      - id: terraform_docs
        name: Terraform docs
        description: Inserts input and output documentation into README.md
        entry: terraform-docs
        language: system
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$
        pass_filenames: false

      - id: terraform_tflint
        name: Terraform lint
        description: Validates all Terraform configuration files with TFLint
        entry: tflint
        language: system
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
