# Pre-commit configuration for Terraform infrastructure
# Uses the same configuration as the centralized cicd repository

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        exclude: '(.terraform|.history)/'
      - id: terraform_validate
        exclude: '(.terraform|.history)/'
      - id: terraform_docs
        exclude: '(.terraform|.history)/'
      - id: terraform_tflint
        exclude: '(.terraform|.history)/'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
